services:
    lotusjeff.dynamic.listener:
        class: lotusjeff\dynamic\event\listener
        arguments:
            - @config
            - @template
            - @user
        tags:
            - { name: event.listener }
